### PR TITLE
Added the possibility for the user to add the 'onShow', and 'onHide' options, which are functions that execute before and after the popover is shown

### PR DESCRIPTION
**Pull request by amisarca**
Hi,

I thought it would be nice to allow the users to add a function that is executed right before the popover is shown, and another one that is executed right after the popover is closed. For example, in my project, I had to perform an AJAX call to display the content of the popover, so a function like this was crucial.

I implemented these changes, by calling the onShow parameter function at the beginning of the show function, and the onHide parameter at the end of the hide function.

Best regards,
Andrei

### CODE REVIEW

**Comment by alexkingorg** [comment]
I would expect this requirement is already solved by the popover-show and popover-hide events that are triggered.

**Comment by amisarca** [comment]
As in?

**Comment by alexkingorg** [comment]
You can run code before/after already using those triggers.

**Comment by amisarca** [comment]
How?

**Comment by alexkingorg** [comment]
Here are some links that might be useful:

http://api.jquery.com/on/
http://api.jquery.com/category/events/

**Pull request closed without merging**
